### ISSUE TITLE
FeatureAttributionSequenceOutput has no __repr__ implemented

### ISSUE THREAD

**Issue by jumelet** [inseq-team/inseq#175]
## 🐛 Bug Report

I am running IG attributions for a list of strings, and was trying to work with the resulting `inseq.data.attribution.FeatureAttributionOutput` object. To inspect what is in there I was looking at the `sequence_attributions`, but I can't print this object because the objects in there don't have a `__repr__` method.

### Code sample

```python
import inseq

model = inseq.load_model("gpt2", "integrated_gradients")

sens = ["this is the first sentence. followed by a second"]
prefix = [sen[:sen.index('.')+1] for sen in sens]

attributions = model.attribute(
    prefix,
    generated_texts=sens,
    n_steps=500,
    internal_batch_size=50
)

print(attributions.sequence_attributions)
```
Returns:

```python
TypeError: __repr__ returned non-string (type dict)
```

### Environment

* Google Colab
* Inseq 0.4.0

**Comment by gsarti** [comment]
Hey @jumelet, thanks for highlighting this bug! :smile: 

The fix in the `__repr__` method of the base class `TensorWrapper` is already implemented in #173 , so it will be merged as soon as the feature is completed. In the meantime, you can use `_ = [print(attr) for attr in attributions.sequence_attributions]` to obtain a similar behavior, or simply `print(attributions.sequence_attributions[0])` to visualize the single object.
