### ISSUE TITLE
allow negative values for `attr_pos_end` parameter

### ISSUE THREAD

**Issue by lsickert** [inseq-team/inseq#181]
Allow negative values for `attr_pos_end`

## Description

allow negative values to be defined for the `attr_pos_end` parameter. 

## Motivation

This would make it possible to e.g. define that the last token (which is often just the EOS token) should be removed from the generated attributions. It probably needs to be evaluated if this is possible for batched attributions, but I think at least for singular attributions, it could be a nice quality-of-life feature. Especially when attributing over multiple sentences where using a positive value is more complicated due to different sentence lengths.

## Commit to Help

- [x] I'm willing to help with this feature.

**Comment by gsarti** [comment]
Hi @lsickert , this should already be possible thanks to the PR that was merged today by installing from the main branch (predicting issues before they are opened! 😄) Could you confirm whether it matches the usage you describe here?

**Comment by lsickert** [comment]
Oh wow, that great. I will take a look later today

**Comment by lsickert** [comment]
Yes, that does look pretty much like what I had in mind. I will close the issue then.
