### ISSUE TITLE
Bug about get_scores_dicts() function

### ISSUE THREAD

**Issue by Betswish** [inseq-team/inseq#185]
## 🐛 Bug Report

Hello, thanks for your contribution firstly! The tool is really helpful and beautiful.
However, when I try to use get_scores_dicts() to output the attributions, I got an error 'index out of bounds'.
![image](https://github.com/inseq-team/inseq/assets/131008659/66b6c6f4-18cc-465c-9524-d4f2802190f2)
I print out the **aggr** and find it seems to be a bug:
![image](https://github.com/inseq-team/inseq/assets/131008659/d6d542df-c56f-43f1-a4f2-e913812e25cd)

## 🔬 How To Reproduce

```python
import inseq
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
import pandas as pd

model = AutoModelForCausalLM.from_pretrained("bigscience/bloom-560m")
tokenizer = AutoTokenizer.from_pretrained("bigscience/bloom-560m")

data = [
        {
            'prompt': 'people usually take shower in the',
            'target_true': ' morning',
            'target_false': ' evening',
            }]

for layer in range(24):
    print('layer:', str(layer))
    attrib_model = inseq.load_model(
        model,
        "layer_gradient_x_activation",
        tokenizer="bigscience/bloom-560m",
        target_layer=model.transformer.h[layer].mlp,
    )
    for i, ex in enumerate(data):
        print(ex)
        # e.g. "The capital of Spain is"
        #prompt = ex["relation"].format(ex["subject"])
        prompt = ex["prompt"]
        # e.g. "The capital of Spain is Madrid"
        true_answer = prompt + ex["target_true"]
        # e.g. "The capital of Spain is Paris"
        false_answer = prompt + ex["target_false"]
        # Contrastive attribution of true vs false answer
        out = attrib_model.attribute(
            prompt,
            true_answer,
            attributed_fn="contrast_prob_diff",
            contrast_targets=false_answer,
            step_scores=["contrast_prob_diff"],
            show_progress=False,
        )
        out.show()
        out.get_scores_dicts()
```

### Environment

* OS: Linux
* Python version: 3.11
* Inseq version: 0.5.0.dev0

**Comment by gsarti** [comment]
Hi @saxenarohit, this issue refers to the current version (`v0.5.0.dev0`) of `inseq` available on the main branch, that can be installed with `pip install git+https://github.com/inseq-team/inseq.git@main`. If you are receiving this error it's because you are likely using `v0.4.0` or previous, where contrast inputs still needed to be preprocessed manually. You can refer to the [Inseq tutorial](https://github.com/inseq-team/inseq/blob/main/examples/inseq_tutorial.ipynb) after upgrading your local version for additional examples of usage. Hope it helps!

**Comment by gsarti** [comment]
@saxenarohit yes please, and add as much detail as possible (code snippet you used, full stack trace). Thanks in advance!
