### ISSUE TITLE
implementation of get_post_variable_assignment_hook

### ISSUE THREAD

**Issue by martijnvanbeers** [inseq-team/inseq#194]
## Question

I'm not sure if I'm looking in the wrong places, or if it is missing, but I cannot find an implementation for `get_post_variable_assignment_hook` which is mentioned in `inseq.utils`' s `__all__` and used in the value-zeroing implementation.

## Checklist

- [x] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

**Comment by martijnvanbeers** [comment]
Of course I find it after I submit this. For some reason my first search on github didn't turn it up, and then I continued with grep on a checkout, but didn't realize I had to look in the branch/pull request.

**Comment by gsarti** [comment]
Hey @martijnvanbeers, indeed the mention of `get_post_variable_assignment_hook` slipped into main but is actually a WIP for methods requiring mid-forward interventions that is currently been developed in #173. 

Note that the method in the branch is a naive (but functional, afaik) implementation hooking the stack tracer. However, it is likely we'll move forward with something more robust such as [torch.fx](https://pytorch.org/docs/stable/fx.html), as I mentioned in [the related PR](https://github.com/inseq-team/inseq/pull/173#issuecomment-1594288157).

Please let me know if you have thoughts about this, or if you would be interested in giving it a shot!
