### ISSUE TITLE
Confusing call of `merge_attributions` method

### ISSUE THREAD

**Issue by DanielSc4** [inseq-team/inseq#209]
## Description

The `merge_attributions` method of the `FeatureAttributionOutput` class can be used as static but also called from an object, instance of that class.
In the latter case, the method's output turns out to be unintended since attribution merge is performed only for the objects in the parameter list and not with the object itself calling the method.
Therefore, it would be advisable to move the method out of the class to be used as a utility.

## Motivation

See above.

## Additional context

Example code used as a demonstration of the method behaviour:
```python
>>> import inseq
>>> seq_model = inseq.load_model('gpt2', attribution_method='input_x_gradient')
>>> out1 = seq_model.attribute(input_texts=['hello world!', 'How are you? '])
>>> out2 = seq_model.attribute(input_texts=['I am going to ', 'My name is '])
```

Correct usage:
```python
>>> inseq.FeatureAttributionOutput.merge_attributions([out1, out2])
FeatureAttributionOutput({
    sequence_attributions: list with 4 elements of type GranularFeatureAttributionSequenceOutput:[
...
```

Misleading behaviour, leading to the loss of attributions contained in `out1`:
```python
>>> out1.merge_attributions([out2])
FeatureAttributionOutput({
    sequence_attributions: list with 2 elements of type GranularFeatureAttributionSequenceOutput:[
...
```

## Commit to Help

- [x] I'm willing to help with this feature.

**Comment by gsarti** [comment]
Thanks for opening this! Would you be willing to open a PR to move the method to a function in the `inseq.data.attribution` file (after `get_batch_from_inputs`)? You would also need to add the function to `inseq.data.__init__` and then `inseq.__init__` to make it available from the root namespace. Thanks in advance! :slightly_smiling_face:
