### ISSUE TITLE
How can I anaylse integrated_gradients for Decoder-Only models?

### ISSUE THREAD

**Issue by MaggieK410** [inseq-team/inseq#214]
## Question
I am trying to vizualize the outputs of a finetuned BioGPT model that I have trained and saved. When I add the input text, which is something like this: "Diagnose: <Patient Info> Diagnoses: <List of Diagnoses>". However, I am getting this error: AssertionError: Forced generations with decoder-only models must start with the input texts.

## Additional context
I am loading the model and then trying to get the integrated_gradients like this: 
out = model.attribute(
    input_texts=outputs,
    attribute_target=True,
    method="attention"
).show()

The input_texts here are, as shown above, "Diagnose: <Patient Info> Diagnoses: <List of Diagnoses>". I am not sure, where my mistake is and would greatly appreciate any help!

**Comment by gsarti** [comment]
Hi @MaggieK410,

I tried to reproduce your issue using `microsoft/biogpt` from the HF Hub (I'm using 4bit mode for convenience, but it shouldn't change anything in practice). I can produce attention attributions without issues as follows:

```python
import inseq
from transformers import AutoModelForCausalLM

model_name = "microsoft/biogpt"
model_4bit = AutoModelForCausalLM.from_pretrained(model_name, device_map="cuda:0", load_in_4bit=True)
model = inseq.load_model(model_4bit, "attention", tokenizer=model_name)
input_texts = "Diagnose: Diagnoses: "
out = model.attribute(
    input_texts=input_texts,
    attribute_target=True,
    method="attention",
).show()
```

![image](https://github.com/inseq-team/inseq/assets/16674069/73d640dc-f0de-4816-b90b-8847dcf8f7ba)

In general, the exception you report is produced when you're trying to force a `generated_texts` parameter to `model.attribute` that doesn't start with the text provided for `input_texts`. It's surprising you receive this error without specifying a value `generated_texts`, you could maybe try removing the space at the end of the prompt (i.e. `Diagnose: Diagnoses:`) to see whether you still face this issue.

For further questions and discussions I can recommend that you join the Inseq Discord channel! You can find the invite link here: https://discord.gg/V5VgwwFPbu

**Comment by MaggieK410** [comment]
Thank you so much for this response, it has solved the issue! I will close it now.

**Comment by MaggieK410** [comment]
So, I have tried to remove the space and used "Diagnose: Diagnoses:" and then it works, but as soon, as I add anything in between (Like "Diagnose: Age 62 Diagnoses:") I am getting the same error. I am still not specifying generated_texts but using the same. I'm a bit surprised here, do you have any further information about what the problem could be?  I will also look into the discord server link you sent me. Thank you very much for your help!

**Comment by gsarti** [comment]
Thanks for following up on this! I'm a bit puzzled on how having those characters in the prompt could produce such a problem though. Could you provide a minimal example of a prompt containing these symbols that produces the error you encountered?

**Comment by MaggieK410** [comment]
Thanks for coming back to me! 

So, in my training prompts I have some delimiters added. One of them would be <A> for age. 
This works: "Diagnose: Age 67 Diagnoses:"
But this does not: "Diagnose: 67 <A> Diagnoses: "

As soon as "<", ">", "_" , "/", "%" etc. are in the prompt, it throws this error, which is a pity, because other than age, I also include lab results (like "red blood cells 3.36 m/ul" or "rdw 16.0 %"). I am also a bit confused, what exactly causes the issue. I have also joined the Discord server (Margareta Anna Kulcsar) and was actually just about to ask in the chat, so of that is easier, I can answer there. Thanks again for your help, I really appreciate it!
