### ISSUE TITLE
On the interoperability with ferret

### ISSUE THREAD

**Issue by romainf28** [inseq-team/inseq#218]
## Question

Thanks for providing a very useful library for applying feature attributions on seq2seq models. I was wondering how you planned on integrating ferret evaluation metrics in Inseq. For instance, will you compute AOPC comprehensiveness for every generated token and then take the average of all the scores ? Or are you planning on designing completely new metrics for the evaluation of feature attributions on seq2seq models ?

**Comment by gsarti** [comment]
Hello @romainf28, thank you for your question!

We do plan to add interoperability between `inseq` and `ferret` soon, and I'll have forthcoming work addressing plausibility evaluation for sequence generation models. 

In general, I think faithfulness evaluation can be naturally extended to sequence generation models in the way you mention, although I recommend using metrics accounting for the magnitude of attribution scores such as Soft-Comprehensiveness and Sufficiency ([Zhao and Aletras, 2023](https://aclanthology.org/2023.acl-long.261/)). On the contrary, I think that the evaluation of plausibility should focus specifically on phenomena (i.e. specific tokens in the generation) for whose there is a human-understandable cue in the preceding context. AUPRC and MRR would be good choices in this latter context.

Hope this helps!

**Comment by romainf28** [comment]
Thank you for your help @gsarti ! You can close the issue. I will join the discord server !

**Comment by junyonglee24** [comment]
@gsarti 
Thank you for your amazing work!

May I please check if the evaluation code for feature attribution has been integrated already? I didn't find relevant codes in the current repo.

Thank you!
