### ISSUE TITLE
Module 'jax' has no attribute 'typing'

### ISSUE THREAD

**Issue by carschno** [inseq-team/inseq#234]
## 🐛 Bug Report

As reported in https://github.com/inseq-team/inseq/issues/232#issuecomment-1807001439, there might be an issue related to `jaxtyping` (#167).

```
AttributeError                            Traceback (most recent call last)
Cell In [1], line 1
----> 1 import inseq

[...]

File /usr/local/lib/python3.9/dist-packages/jaxtyping/_array_types.py:680
    678 PRNGKeyArray = Union[Key[jax.Array, ""], UInt32[jax.Array, "2"]]
    679 Scalar = Shaped[jax.Array, ""]
--> 680 ScalarLike = Shaped[jax.typing.ArrayLike, ""]

AttributeError: module 'jax' has no attribute 'typing'
```

It looks like updating `jax` and/or `jaxlib` has resolved the issue: https://github.com/inseq-team/inseq/issues/232#issuecomment-1807043699

Similar issues in other projects:

- https://github.com/google/jax/issues/6801
- https://github.com/google/brax/issues/224

## 🔬 How To Reproduce

Unclear.

### Code sample

```python
import inseq
```

### Environment

* OS: [e.g. Linux / Windows / macOS]
* Python version, get it with:

```bash
python --version
```

* Inseq version, get it with:
Commit 4d8f688c0cbb39f0f90ce4f15c8f120c51f232fe (probably)

## Expected behavior

Import Inseq without errors, with or without `jax`/`jaxlib` being installed.

## Additional context

Currently, Jax is not a dependency of Inseq. However, many users will have Jax installed. We need to make sure that Inseq works and possibly document/pin Jax versions that are compatible.

**Comment by carschno** [comment]
I have not yet been able to reproduce the issue. @seemavishal would you be able to provide the Jax/Jaxlib versions you had installed before updating them (which apparently resolved the issue)?

**Comment by carschno** [comment]
Trying different combinations of `jax` and `jaxlib` versions, all with Python 3.9.
Checking whether ```import inseq``` works:

| status | | | | | | |
| ------ | -------- | - | - | - | - | - |
| jax | not installed | 0.3.0 | 0.3.0 | 0.4.0 | 0.4.20 | 0.4.20 |
| jaxlib | not installed | not installed | 0.4.0 | 0.4.0 | 0.4.0 | 0.4.20 | 
| works | ✔️ | ✔️ | ❌  [^1] | ❌ [^2]  | ❌ [^3] | ✔️ | 

[^1]: `RuntimeError: jaxlib version 0.4.0 is newer than and incompatible with jax version 0.3.0` 
[^2]: `AttributeError: module 'jax' has no attribute 'typing'`
[^3]: `RuntimeError: jaxlib is version 0.4.0, but this version of jax requires version >= 0.4.14.`

We are interested in error case 2 here, so it looks like a recent version of both `jax` and `jaxlib` is required.

**Comment by seemavishal** [comment]
Hi,

To resolve the error related to jaxlib I tried pip install -U jaxlib.

That resolved the problem.
