### ISSUE TITLE
Contrastive explanations

### ISSUE THREAD

**Issue by JanAthmer** [inseq-team/inseq#239]
## 🐛 Bug Report

In the demo code for contrastive explanations there is an argument error, which means it doesn't run. There is an argument that isn't used, namely the target sentence. It needs token_ids and token_masks of this target sentence. I assume there is a naming error which makes it not go through the tokenizer.

## 🔬 How To Reproduce

1. Copy paste the demo code.

### Code sample

import inseq

attribution_model = inseq.load_model("gpt2", "saliency")

out = attribution_model.attribute(
    "The manager went home because",
    "The manager went home because he was sick",
    attributed_fn="contrast_prob_diff",
    contrast_targets="The manager went home because she was sick",
    step_scores=["contrast_prob_diff"]
)
out.show()

### Environment

* OS: [e.g. Linux]
* Python version, get it with: '3.9.5 [GCC 10.3.0]'

```bash
python --version
```

* Inseq version, get it with:

```bash
python -c "import inseq; print(inseq.get_version())"
```

**Comment by gsarti** [comment]
Hi @JanAthmer, I think it's likely that you're using v0.4 where contrastive ids and attention mask are required instead of the plain text string. The example you provided works fine with the new release (v0.5, see [release notes](https://github.com/inseq-team/inseq/releases/tag/v0.5.0)). You should be able to upgrade with `pip install -U inseq`!

**Comment by JanAthmer** [comment]
I just installed it this morning and even tried the dev release, so I don't think it's a version issue. Checking the version I have version 0.5.

**Comment by gsarti** [comment]
I tested both v0.5 and `latest` and I am able to run it no problem! Could you paste the error trace you obtain when you try to run this? Might also be due to older versions of `transformers` and `torch`

**Comment by JanAthmer** [comment]
Ye I have some conflict with packages I think because if I do it in a clean environment it works fine.

**Comment by JanAthmer** [comment]
One quick question; do you have any sight on when there will be support for: _"Multi-sentence attribution and methods expanding inputs to multiple steps (e.g. Integrated Gradients) are not yet supported for contrastive attribution."_ ? That would be super nice 👀
