### ISSUE TITLE
Does inseq work with Mistral-7B or Llama-2-7B models?

### ISSUE THREAD

**Issue by hadiasghari** [inseq-team/inseq#265]
## Question

Hello, I was wondering if `inseq` works with either Mistral-7B or Llama-2-7B models? I can load the models without an issue and run the tutorial's minimum pair example ("The manager went home because..."). But the resulting saliency heatmap looks quite off (screenshot below).

## Additional context

I run the following code:

```
from transformers import AutoModelForCausalLM, AutoTokenizer
import inseq

model_name =  "mistralai/Mistral-7B-Instruct-v0.2"  # or "meta-llama/Llama-2-7b-chat-hf" 
access_token = "XXX"  # needed because models are gated
hf_model = AutoModelForCausalLM.from_pretrained(model_name, token=access_token).cuda()
hf_tkz = AutoTokenizer.from_pretrained(model_name, token=access_token)

attrib_model = inseq.load_model(hf_model, "integrated_gradients", tokenizer=hf_tkz)
out = attrib_model.attribute(
    input_texts=["The manager went home because", "The manager went home because"],
    generated_texts=["The manager went home because he was sick.", "The manager went home because she was sick."],
    step_scores=["probability"],
)
out[0].aggregate("pair", paired_attr=out[1], do_post_aggregation_checks=False).show()
```

This results in the following saliency heatmap. The probabilities in the last row seem correct. But one would expect the cell for manager/he→she to be high/very red, which isn't the case. 

![saliencymap_mistral_minpair_20240422](https://github.com/inseq-team/inseq/assets/5025042/b48e10a1-72bd-4356-a1b5-112e63443319)

## Checklist

- [X] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

Thanks!

**Comment by gsarti** [comment]
Hi @hadiasghari, any update on this? Can I close the issue?
